"""initial migration

Revision ID: 5e4f4615953b
Revises: 214002932dbf
Create Date: 2025-09-21 18:08:41.137175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4f4615953b'
down_revision: Union[str, None] = '214002932dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_center',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('adoption_center_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['adoption_center_id'], ['adoption_center.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_pet_center', 'pet', ['adoption_center_id'], unique=False)
    op.create_index('idx_pet_species_birthdate', 'pet', ['species', 'birth_date'], unique=False)
    op.create_index(op.f('ix_pet_created_at'), 'pet', ['created_at'], unique=False)
    op.create_index(op.f('ix_pet_name'), 'pet', ['name'], unique=False)
    op.create_table('adoption_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('available', 'in_process', 'adopted', name='adoptionstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('vaccine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine')
    op.drop_table('adoption_status')
    op.drop_index(op.f('ix_pet_name'), table_name='pet')
    op.drop_index(op.f('ix_pet_created_at'), table_name='pet')
    op.drop_index('idx_pet_species_birthdate', table_name='pet')
    op.drop_index('idx_pet_center', table_name='pet')
    op.drop_table('pet')
    op.drop_table('adoption_center')
    # ### end Alembic commands ###
